### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by IT-Mohsin** [JuergenGutsch/GraphQlDemo#1]
I saw few different approaches with .Net Core GraphQL API.
1.  Middleware
2.  Controller 
3. With out both (No Middleware and No Controller)

Which one to choose in what situation.
Please help.

**Comment by JuergenGutsch** [comment]
Hi @IT786 

I prefer the Middleware way, because it separates the GraphQL from MVC. IMHO MVC Pattern and GraphQL don't really match.

**Comment by drowhunter** [comment]
Why is the book repository in a file call person repository?

**Comment by JuergenGutsch** [comment]
Hi @drowhunter, because I just forgot to rename the file. Feel free to rename it and to create a PR. I'll take it in then
